// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
    /**
     * public static final class DriveConstants {
     * public static final int kLeftMotor1Port = 0;
     * public static final int kLeftMotor2Port = 1;
     * public static final int kRightMotor1Port = 2;
     * public static final int kRightMotor2Port = 3;
     * }
     */

    public static final class PID {
        //
        public static final double P = 2.4f;
        public static final int I = 0;
        public static final double D = 0.1f;
        //
        public static final int P2 = 60;
        public static final int I2 = 0;
        public static final int D2 = 6;
        //
    }

    public static final class Positions {

        //Stored
        public static final int lowerStored = 0;
        public static final int upperStored = 10;

        //L1
        public static final int lowerFirst = 0;
        public static final int upperFirst = 5;

        //L2
        public static final int lowerSecond = 0;
        public static final int upperSecond = 10;

        //L3
        public static final int lowerThird = 5;
        public static final int upperThird = 10;

        //L4
        public static final int lowerFourth = 10;
        public static final int upperFourth = 10;

        //Climb
        public static final int lowerClimb = -5;
        public static final int upperClimb = 0;

        //Ground Pickup
        public static final int lowerGround = 0;
        public static final int upperGround = 0;
        
        //Source Pickup
        // public static final int lowerSource = 0;
        // public static final int upperSource = 0;

        //Processor Place
        // public static final int lowerProcessor = 0;
        // public static final int upperProcessor = 0;
    }
}
